### Good request
POST http://localhost:8000/sales

{
    "time": "2024-08-06T08:58:14+00:00",
    "customer_id": "c6",
    "sku": "puzzle-42",
    "amount": 1,
    "price": 12.34
}


### Get sale (change ID)
GET http://localhost:8000/sales/e85451c50f33457ba8145a84f4310581

### Empty customer ID
POST http://localhost:8000/sales

{
    "time": "2024-08-06T08:58:14+00:00",
    "customer_id": "",
    "sku": "puzzle-42",
    "amount": 1,
    "price": 12.34
}
